/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package copiafacil;

import javax.swing.JOptionPane;

/**
 *
 * @author edsoo
 */
public class CadastrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPedido
     */
    public CadastrarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Descricao = new javax.swing.JTextField();
        Prazo = new javax.swing.JTextField();
        Quantidade = new javax.swing.JTextField();
        Sair = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        Id_Cliente = new javax.swing.JTextField();
        Preco_Unitario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, -1));
        getContentPane().add(Prazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 130, -1));

        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, -1));

        Sair.setContentAreaFilled(false);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 60, 30));

        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 60, 20));

        Cadastrar.setContentAreaFilled(false);
        Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 60, 20));
        getContentPane().add(Id_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, -1));
        getContentPane().add(Preco_Unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Página_menu_Cadastrar_Pedidos.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 537, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here
        new PáginaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        PedidoCadastrado pedidoscadastrados = new PedidoCadastrado();
            String idClienteText = Id_Cliente.getText();
          pedidoscadastrados.setDescricao(Descricao.getText());
           pedidoscadastrados.setPrazo(Prazo.getText());
          
            
          
            String quant = Quantidade.getText();
           String preco = Preco_Unitario.getText();
             if (idClienteText.isEmpty() || quant.isEmpty() || preco.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
           
            int idCliente = Integer.parseInt(idClienteText);
            int quantidade = Integer.parseInt(quant);
            float precoUnitario = Float.parseFloat(preco);
            PedidoCadastradoDAO dao = new PedidoCadastradoDAO();

            boolean clienteExiste = dao.verificarClienteExistente(idCliente);
            

            if (!clienteExiste) {
                JOptionPane.showMessageDialog(null, "ID do cliente inválido");
                new CadastrarPedido().setVisible(true);
                this.dispose();
                return;
            } 

            pedidoscadastrados.setId_Cliente(idCliente);
            
            pedidoscadastrados.setQuantidade(quantidade);
            
            pedidoscadastrados.setPreco_Unitario(precoUnitario);
            dao.adiciona(pedidoscadastrados);
            float valor = dao.calcularValorPedido(idCliente);

            JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso");
            JOptionPane.showMessageDialog(null, "Valor: " + valor);
        }
    Id_Cliente.setText("");
    Prazo.setText("");
    Preco_Unitario.setText("");
    Quantidade.setText("");   
    Descricao.setText(""); 
    }//GEN-LAST:event_CadastrarActionPerformed

    private void DescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescricaoActionPerformed

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
         if (LoginFuncionario.role.equals("ADMIN")) {
    // Show admin menu
            new MenuAdm().setVisible(true);
            
            this.dispose();
} else if (LoginFuncionario.role.equals("FUNCIONARIO")) {
    new MenuFuncionario().setVisible(true);
            
            this.dispose();
} else {
    // Handle invalid role or show a default menu
    JOptionPane.showMessageDialog(this, "Função inválida, fechando o software.");
    
    this.dispose();
}
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField Descricao;
    private javax.swing.JTextField Id_Cliente;
    private javax.swing.JTextField Prazo;
    private javax.swing.JTextField Preco_Unitario;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
