/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package copiafacil;

import javax.swing.JOptionPane;

/**
 *
 * @author edsoo
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionario
     */
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cargo = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Telefone = new javax.swing.JTextField();
        CPF = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Senha = new javax.swing.JPasswordField();
        Sair = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 150, -1));
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 150, -1));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, -1));
        getContentPane().add(Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 140, -1));
        getContentPane().add(CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, -1));

        Cadastrar.setContentAreaFilled(false);
        Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 60, 20));

        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                VoltarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 60, 20));
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, -1));

        Sair.setContentAreaFilled(false);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 60, 30));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Página menu Cadastrar Funcionário (4).png"))); // NOI18N
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 539, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        new PáginaInicial().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void VoltarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_VoltarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarAncestorAdded

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        new MenuAdm().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        Funcionario funcionarios = new Funcionario();
            funcionarios.setNome(Nome.getText());
            funcionarios.setTelefone(Telefone.getText());
            funcionarios.setCargo(Cargo.getText());
            funcionarios.setEmail(Email.getText());
            funcionarios.setCpf(CPF.getText());
            funcionarios.setSenha(Senha.getText());
            
            
            /*
                private String Nome;
    private String Telefone;
    private String Endereco; 
    private String Email; 
    private String Cpf; 
            */
            if (
                    (CPF.getText().isEmpty()) ||
                    (Telefone.getText().isEmpty()) ||
                    (Email.getText().isEmpty()) ||
                    (Cargo.getText().isEmpty()) ||
                      (Senha.getText().isEmpty()) ||
                    (Nome.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
                
            }
            else{
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.adiciona(funcionarios);
            JOptionPane.showMessageDialog(null, " Funcionario "+Nome.getText()+" Inserido(a) com sucesso! ");
    }
    
    CPF.setText("");
    Telefone.setText("");
    Email.setText("");
    Nome.setText("");
    Senha.setText("");
    Cargo.setText("");
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPF;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField Cargo;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Sair;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JTextField Telefone;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
